spec:
  template:
    spec:
      containers:
      - name: bases-de-datos
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "redis_secret"
