# Docker Compose for HR SaaS with Supabase
version: '3.8'

services:
  # Supabase local development (alternative to supabase start)
  # Use this if you want more control over the services
  
  # Frontend Application
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - supabase-api
    networks:
      - hr-network

  # Optional: Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - hr-network

  # Optional: Nginx for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge

volumes:
  redis-data:

# Note: Supabase services are managed by `supabase start`
# This compose file is for additional services and your application
