[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]  
cmds = [
  "export NEXT_CACHE=/tmp/next-cache && npm run build"
]

[start]
cmd = "npm run start"

# Prevent Railway from auto-mounting .next/cache
[variables]
NIXPACKS_NO_CACHE_MOUNT = "true"