[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

# Environment variables for Railway
[variables]
TZ = "America/Tegucigalpa"
NODE_ENV = "production"
PORT = "8080"
HOSTNAME = "0.0.0.0"

# Railway-specific configurations
[railway]
serviceType = "web"
