apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomina
  namespace: saas-rh
  labels:
    app: nomina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nomina
  template:
    metadata:
      labels:
        app: nomina
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
      containers:
      - name: nomina
        image: 826726045450.dkr.ecr.us-east-1.amazonaws.com/nomina:latest
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3002
        env:
        - name: BASE_PATH
          value: "/nomina"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        volumeMounts:
        - name: nomina-storage
          mountPath: /app/pdfs
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: nomina-storage
        persistentVolumeClaim:
          claimName: nomina-pvc
