apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomina
  labels:
    app: nomina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nomina
  template:
    metadata:
      labels:
        app: nomina
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
      containers:
      - name: nomina
        image: 826726045450.dkr.ecr.us-east-1.amazonaws.com/nomina:latest
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: url
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: pdf-storage
          mountPath: /app/pdfs
          readOnly: false
      volumes:
      - name: pdf-storage
        persistentVolumeClaim:
          claimName: nomina-pvc
