apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: saas-rh
type: Opaque
stringData:
  # These values should be replaced during deployment
  access_key_id: ""
  secret_access_key: ""
