apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas-rh-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - asistencia.saas-rh.com
    - nomina.saas-rh.com
    secretName: saas-rh-tls
  rules:
  - host: asistencia.saas-rh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asistencia
            port:
              number: 80
  - host: nomina.saas-rh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nomina
            port:
              number: 80
