apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: saas-rh
type: Opaque
stringData:
  username: admin
  password: "your-db-password"  # Replace with actual secret or use Helm template
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: saas-rh
type: Opaque
stringData:
  secret: "your-jwt-secret"  # Replace with actual secret or use Helm template
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: saas-rh
type: Opaque
stringData:
  password: "your-redis-password"  # Replace with actual secret or use Helm template
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: saas-rh
  labels:
    app: saas-rh
    environment: staging

# Non-sensitive environment variables
  
data:
  DB_HOST: postgres
  DB_USER: admin
  DB_NAME: saas_db_staging
  PORT: "3000"
  CORS_ORIGIN: "http://localhost:3010,http://localhost:3012,http://localhost:3013"
