apiVersion: v1
kind: Service
metadata:
  name: asistencia
  namespace: saas-rh
  labels:
    app: asistencia
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: asistencia
