apiVersion: v1
kind: Service
metadata:
  name: bases-de-datos
  namespace: saas-rh
  labels:
    app: bases-de-datos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: bases-de-datos
