apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomina
  namespace: default
  labels:
    app: nomina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nomina
  template:
    metadata:
      labels:
        app: nomina
    spec:
      containers:
        - name: nomina
          image: 826726045450.dkr.ecr.us-east-1.amazonaws.com/nomina:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: PORT
              value: "3000"
            - name: CORS_ORIGIN
              value: "https://app.humanosisu.com,https://api.humanosisu.com"
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30 # Allow up to 2.5 minutes for startup
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
