apiVersion: v1
kind: Service
metadata:
  name: nomina
  namespace: saas-rh
  labels:
    app: nomina
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nomina
