apiVersion: apps/v1
kind: Deployment
metadata:
  name: bases-de-datos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bases-de-datos
  template:
    metadata:
      labels:
        app: bases-de-datos
    spec:
      containers:
        - name: bases-de-datos
          image: your-registry/bases_de_datos:latest
          envFrom:
            - secretRef:
                name: bases-de-datos-secret
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: bases-de-datos
spec:
  selector:
    app: bases-de-datos
  ports:
    - port: 3001
      targetPort: 3001
