import {
  AlertTriangle,
  BadgeDollarSign,
  Building2,
  Calculator,
  Calendar,
  ChartSpline,
  Check,
  Clock3,
  Crosshair,
  Database,
  Download,
  Eye,
  FileText,
  Filter,
  Lightbulb,
  Mail,
  MessageSquare,
  Minus,
  PartyPopper,
  Pencil,
  Phone,
  Plus,
  ReceiptText,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Trophy,
  UserRound,
  Users,
  X,
} from 'lucide-react'
import React from 'react'

const ICONS = {
  download: Download,
  user: UserRound,
  alert: AlertTriangle,
  building: Building2,
  users: Users,
  calendar: Calendar,
  clock: Clock3,
  money: BadgeDollarSign,
  check: Check,
  warning: AlertTriangle,
  gear: Settings,
  edit: Pencil,
  send: Send,
  rocket: Rocket,
  refresh: RefreshCw,
  close: X,
  search: Search,
  filter: Filter,
  chart: ChartSpline,
  receipt: ReceiptText,
  envelope: Mail,
  whatsapp: MessageSquare,
  target: Crosshair,
  document: FileText,
  calculator: Calculator,
  database: Database,
  shield: ShieldCheck,
  trophy: Trophy,
  lightbulb: Lightbulb,
  party: PartyPopper,
  phone: Phone,
  plus: Plus,
  minus: Minus,
  eye: Eye,
} as const

export type IconName = keyof typeof ICONS

export function Icon({ name, className, ...props }: { name: IconName; className?: string } & React.SVGProps<SVGSVGElement>) {
  const C = ICONS[name]
  if (!C) return null
  return <C className={className} {...props} />
}
