/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/payroll/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar preview de nómina
         * @description Genera un preview de nómina para un período específico.
         *     No modifica datos - solo calcula y retorna resultados.
         *
         */
        post: operations["previewPayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calcular y guardar nómina
         * @description Calcula nómina y la guarda en la base de datos.
         *     Crea payroll_run y payroll_run_lines.
         *
         */
        post: operations["calculatePayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payroll/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autorizar nómina
         * @description Autoriza una corrida de nómina existente.
         *     Requiere If-Match header para control de concurrencia.
         *
         */
        post: operations["authorizePayroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PreviewInput: {
            /**
             * Format: date-time
             * @description Inicio del período en RFC 3339 UTC
             * @example 2025-01-01T00:00:00Z
             */
            period_start: string;
            /**
             * Format: date-time
             * @description Fin del período en RFC 3339 UTC
             * @example 2025-01-15T23:59:59Z
             */
            period_end: string;
            /**
             * Format: uuid
             * @description UUID de la empresa
             * @example 00000000-0000-0000-0000-000000000001
             */
            company_id: string;
            /**
             * @description Tipo de ciclo de pago
             * @example quincena
             * @enum {string}
             */
            pay_cycle: "quincena";
            /**
             * @description Tipo de cálculo (CON/SIN deducciones)
             * @example CON
             * @enum {string}
             */
            calculation_type?: "CON" | "SIN";
        };
        AuthorizeInput: {
            /**
             * Format: uuid
             * @description UUID de la corrida a autorizar
             * @example 38ea2a3d-b9d9-442d-98a1-131e6150c82f
             */
            run_id: string;
        };
        Resumen: {
            /**
             * @description Número total de empleados
             * @example 34
             */
            empleados: number;
            /**
             * Format: float
             * @description Total de salarios brutos
             * @example 45000
             */
            total_bruto: number;
            total_deducciones: components["schemas"]["TotalDeducciones"];
            /**
             * Format: float
             * @description Total de salarios netos
             * @example 38000
             */
            total_neto: number;
            /**
             * @description Total de días trabajados
             * @example 510
             */
            total_dias_trabajados: number;
            /**
             * Format: float
             * @description Total de horas extras
             * @example 0
             */
            total_horas_extras: number;
        };
        TotalDeducciones: {
            /**
             * Format: float
             * @description Total deducciones IHSS
             * @example 2250
             */
            IHSS: number;
            /**
             * Format: float
             * @description Total deducciones RAP
             * @example 675
             */
            RAP: number;
            /**
             * Format: float
             * @description Total deducciones ISR
             * @example 1800
             */
            ISR: number;
            /**
             * Format: float
             * @description Otras deducciones
             * @example 0
             */
            otros: number;
        };
        PlanillaRow: {
            /**
             * Format: uuid
             * @description UUID del empleado
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            employee_id: string;
            /**
             * @description Nombre completo del empleado
             * @example Juan Pérez
             */
            name: string;
            /**
             * Format: float
             * @description Salario base mensual
             * @example 15000
             */
            base_salary: number;
            /**
             * Format: float
             * @description Total de ingresos (salario + extras)
             * @example 7500
             */
            total_earnings: number;
            /**
             * Format: float
             * @description Deducción IHSS
             * @example 375
             */
            IHSS: number;
            /**
             * Format: float
             * @description Deducción RAP
             * @example 112.5
             */
            RAP: number;
            /**
             * Format: float
             * @description Deducción ISR
             * @example 300
             */
            ISR: number;
            /**
             * Format: float
             * @description Total de deducciones
             * @example 787.5
             */
            total_deducciones: number;
            /**
             * Format: float
             * @description Salario neto final
             * @example 6712.5
             */
            total: number;
            /**
             * @description Días trabajados en el período
             * @example 15
             */
            days_worked: number;
            /**
             * @description Días ausentes en el período
             * @example 0
             */
            days_absent: number;
            /**
             * @description Días con llegadas tardías
             * @example 0
             */
            late_days: number;
            /**
             * @description Departamento del empleado
             * @example Ventas
             */
            department?: string | null;
            /**
             * Format: uuid
             * @description UUID de la línea de nómina (null en preview)
             * @example null
             */
            line_id?: string | null;
        };
        PreviewOutput: {
            /**
             * Format: uuid
             * @description UUID de la corrida generada
             * @example 38ea2a3d-b9d9-442d-98a1-131e6150c82f
             */
            run_id: string;
            /**
             * @description Estado actual de la corrida
             * @example draft
             * @enum {string}
             */
            status: "draft" | "edited" | "authorized" | "distributed";
            resumen: components["schemas"]["Resumen"];
            /** @description Array de líneas de nómina */
            planilla: components["schemas"]["PlanillaRow"][];
            /**
             * Format: date-time
             * @description Timestamp de generación en RFC 3339 UTC
             * @example 2025-01-12T19:14:29.666Z
             */
            generated_at: string;
            /**
             * @description ETag para control de concurrencia
             * @example "abc123"
             */
            etag: string;
        };
        AuthorizeOutput: {
            /**
             * Format: uuid
             * @description UUID de la corrida autorizada
             * @example 38ea2a3d-b9d9-442d-98a1-131e6150c82f
             */
            run_id: string;
            /**
             * @description Nuevo estado de la corrida
             * @example authorized
             * @enum {string}
             */
            status: "authorized";
            /**
             * Format: uri
             * @description URL del PDF generado
             * @example /api/v1/payroll/generate-pdf-from-run?run_id=38ea2a3d-b9d9-442d-98a1-131e6150c82f
             */
            artifact_url: string;
            /**
             * @description Número de comprobantes generados
             * @example 34
             */
            vouchers_count: number;
            /**
             * Format: date-time
             * @description Timestamp de autorización en RFC 3339 UTC
             * @example 2025-01-12T19:14:29.666Z
             */
            authorized_at: string;
            /**
             * @description Nuevo ETag de la corrida autorizada
             * @example "def456"
             */
            etag: string;
            summary?: components["schemas"]["Resumen"];
        };
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI que identifica el tipo de problema
             * @example https://docs.humanosisu.net/errors/invalid-transition
             */
            type: string;
            /**
             * @description Título legible del problema
             * @example Invalid state transition
             */
            title: string;
            /**
             * @description Código de estado HTTP
             * @example 409
             */
            status: number;
            /**
             * @description Descripción detallada del problema
             * @example Cannot authorize from draft. Move to edited first.
             */
            detail?: string;
            /**
             * Format: uri
             * @description URI específica de la ocurrencia del problema
             * @example /api/v1/payroll/authorize
             */
            instance?: string;
            /**
             * @description Código interno del error
             * @example INVALID_STATE_TRANSITION
             */
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    previewPayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewInput"];
            };
        };
        responses: {
            /** @description Preview generado exitosamente */
            200: {
                headers: {
                    /** @description ETag del preview generado */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOutput"];
                };
            };
            /** @description Error de validación en entrada */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No autorizado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflicto - período ya procesado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    calculatePayroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewInput"];
            };
        };
        responses: {
            /** @description Nómina calculada y guardada exitosamente */
            201: {
                headers: {
                    /** @description ETag de la corrida creada */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOutput"];
                };
            };
            /** @description Error de validación */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflicto - corrida ya existe */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    authorizePayroll: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag de la corrida a autorizar */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizeInput"];
            };
        };
        responses: {
            /** @description Nómina autorizada exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizeOutput"];
                };
            };
            /** @description Error de validación */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflicto - transición de estado inválida */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Precondition Failed - ETag no coincide */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
