apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-snapshot-class
driver: ebs.csi.aws.com
deletionPolicy: Retain
parameters:
  description: "EBS snapshot for PVC backup"
  csi.storage.k8s.io/snapshotter-secret-name: ebs-csi-snapshotter
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
