apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  host: "postgres"
  port: "5432"
  database: "saas_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  host: "redis"
  port: "6379"
