apiVersion: apps/v1
kind: Deployment
metadata:
  name: bases-de-datos
  labels:
    app: bases-de-datos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bases-de-datos
  template:
    metadata:
      labels:
        app: bases-de-datos
    spec:
      containers:
      - name: bases-de-datos
        image: ${ECR_REGISTRY}/bases-de-datos:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
