apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- configmap.yaml

secretGenerator:
- name: db-credentials
  literals:
  - username=admin
  - password=secret
- name: redis-credentials
  literals:
  - password=redis_secret
- name: app-secrets
  literals:
  - session-secret=your-session-secret-here

commonLabels:
  app: bases-de-datos
