apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nomina-pvc
  namespace: saas-rh
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
